### ISSUE TITLE
Error w/ 2.0.1 and Confluence 5.6.3

### ISSUE THREAD

**Issue by kirbini** [codeclou/advanced-codeblock-macro#2]
This looks like a great plugin for generating network switch code.  However when I had our admin install it (2.0.1) on our 5.6.3 instance we get this error:

Error rendering macro 'advanced-codeblock-macro' : com.atlassian.confluence.xhtml.api.MacroDefinition.getMacroId()Lcom/atlassian/fugue/Option;

Any chance we can fix it or do we need to upgrade?

**Comment by clouless** [comment]
Hi,

That really sounds like the macro tries to call `getMacroID` but the Container (Confluence) does not provide this. Usually I always only bugifx things "roll-forward"-style and not port it back to older versions of the plugin because that only leads to more errors and more overhead.

So maybe really try to upgrade to Confluence 5.9+ that should be the safest.

**Comment by kirbini** [comment]
Understood.  We’re scheduled to upgrade later this year so I guess I’ll just have to wait.  Thanks for the quick response.
-
jk

On Jan 4, 2017, at 2:48 PM, Bernhard Grünewaldt <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

That really sounds like the macro tries to call getMacroID but the Container (Confluence) does not provide this. Usually I always only bugifx things "roll-forward"-style and not port it back to older versions of the plugin because that only leads to more errors and more overhead.

So maybe really try to upgrade to Confluence 5.9+ that should be the safest.
