### ISSUE TITLE
Is it possible to have a setting to choose the default color?

### ISSUE THREAD

**Issue by padraiglennon** [codeclou/advanced-codeblock-macro#7]
Hi. 

This is a nice add-on. Just starting to use it. Would it be difficult to add a setting to define the default color  to allow it to work with some styling customizations we implement. A global setting for example which could be set by the admin?

**Comment by clouless** [comment]
Hi,

good to hear :)

What would be the way you would want to define the styling?
Would it be enough to provide like for example a "dark theme"?

But for the most part I want to keep the features as reduced as possible, since every new feature will
lead to more stuff to test and possibly more bugs. 

Currently I do not see the need for further customizations.


But you could achieve some results with some **global CSS**
  * https://confluence.atlassian.com/doc/styling-confluence-with-css-166528400.html

Then **overwrite the css of highlight js** code with your own CSS (you can use existing themes).
  * https://highlightjs.org/static/demo/

For Example when using `Base16 Atelier Heath Dark - Theme`:

![image](https://user-images.githubusercontent.com/12599965/46216855-c7ab0f80-c340-11e8-86c2-efb7f70e030f.png)

![image](https://user-images.githubusercontent.com/12599965/46216913-ea3d2880-c340-11e8-803e-4281b53ab5d4.png)

**Comment by padraiglennon** [comment]
Wow that was a really quick reply. I'll look into updating the CSS as outlined above. I literally just want to change the purple color to navy. Thanks again for the quicky reply

**Comment by clouless** [comment]
Ok :) Then here is the CSS for changing the purple

```
/* CUSTOM COLOR - ADVANCED CODEBLOCK PLUGIN */
.advanced-codeblock-header {
   background: #000080 !important;
}
.advanced-codeblock-label {
    background-color: #efefef !important;
    color: #000080 !important;
    border: 1px solid #000080 !important;
}
.advanced-codeblock-logo-normal-macro {
    display:none !important; /* hiding the logo */
}
```

it looks like this:

![image](https://user-images.githubusercontent.com/12599965/46219052-99303300-c346-11e8-9153-2bf04aece2c0.png)

**Comment by padraiglennon** [comment]
Excellent. Thank you. I ended up using the following to make it the same color as the default confluence menus

```
.advanced-codeblock-label {
    background-color: #fff;
    color: #0049B0;
    border: 1px solid #0049B0;
}

.advanced-codeblock-header {
    border-color: #cdcdcd;
    color: #fff;
    background-color: #0049B0;
}

.advanced-codeblock-code {
    border-left: 1px solid #0049B0;
    border-right: 1px solid #0049B0;
    border-bottom: 1px solid #0049B0;
}
.advanced-codeblock-logo-normal-macro {
    border-left: 1px solid #0049B0;
    border-right: 1px solid #0049B0;
    border-bottom: 1px solid #0049B0;
}

.advanced-codeblock-logo-normal-macro {
    display:none !important; /* hiding the logo */
}
```

**Comment by clouless** [comment]
cool :) I think that is the easiest way to do it :) 
I will try to keep html and class-naming as stable as possible.

cheers
